### ISSUE TITLE
Action running but no results showing up - how to debug?

### ISSUE THREAD

**Issue by mwarkentin** [reviewdog/action-hadolint#10]
Hello, I've tried to set this action up on one of our repos to lint our Dockerfile with the following config:

```
name: reviewdog
on: [pull_request]
jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          level: info
```

The action runs successfully on my test PR:

![](https://s3.amazonaws.com/mwarkentin-snaps/try_reviewdoghadolint_for_docker_linting_by_mwarkentin__Pull_Request_143__waveaccountinglithograph_2020-04-30_10-10-51.png)

When I run hadolint locally I get the following output:

```
❯ hadolint Dockerfile
Dockerfile:3 DL3006 Always tag the version of an image explicitly
Dockerfile:5 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
Dockerfile:13 DL3003 Use WORKDIR to switch to a directory
Dockerfile:15 DL3006 Always tag the version of an image explicitly
Dockerfile:16 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
```

But I'm not getting any results from reviewdog/hadolint in my PR, or seeing any indication of things failing in the logs. I'm not sure if there are any permissions I need to configure to allow the action to annotate the PR?

I also tried to explicitly add an error to the dockerfile in case the action was filtering it's check based on what was modified:

![](https://s3.amazonaws.com/mwarkentin-snaps/try_reviewdoghadolint_for_docker_linting_by_mwarkentin__Pull_Request_143__waveaccountinglithograph_2020-04-30_10-13-20.png)
