### ISSUE TITLE
Feature: add exclude pattern

### ISSUE THREAD

**Issue by hazcod** [reviewdog/action-hadolint#16]
At the moment we have to do something like:

```yaml
  dockerlint:
    name: Lint - Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: remove vendor dockerfiles
      run: find vendor/ -type f -iname '*dockerfile*' -delete
    - name: hadolint
      uses: reviewdog/action-hadolint@v1.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reviewdog_flags: docker/
```
